### PR TITLE
Merge 'topic/inltables' to 'master'

### LINKED ISSUE #19: writing out inline tables
I have a structure as follows:

        public class UserSettings
        {
            public Dictionary<string, Item> VariableProperties { get; set; }
        }
        public class Item
        {
            public bool Checked { get; set; }
            public string Name { get; set; }
            public string Caption { get; set; }
            public string Unit { get; set; }
            public string NumberFormat { get; set; }
            public string Type { get; set; }
            public bool CalcStats { get; set; }
        }

when this is written back to the source toml file it spans multiple lines, e.g.

[User.VariableProperties]

[User.VariableProperties.fe]
Checked = true
Name = "fe"
Caption = "Fe"
Unit = "%"
NumberFormat = "#0.00"
Type = "column"
CalcStats = true

I'll have a number of entries for this table so I was wondering whether is it possible to write this as an inline table to help readability?  e,g,

[User.VariableProperties]
fe = { Checked = true, Name = "fe", Caption = "Fe", Unit = "%", NumberFormat = "#0.00", Type = "column", CalcStats = true }

### PR DESCRIPTION
**Pull request by paiden**
It is now possible to write items inside collections as inline tables.

To do so the type has to be marked as an inline tables. There are two ways to do so:

```
            var config = TomlConfig.Create(cfg =>
                cfg.ConfigureType<Item>(type =>
                    type.TreatAsInlineTable()));

            var s = Toml.WriteString(new UserSettings(), config);
```
or
```
[TreatAsInlineTable]
public class Item {... }
```

Closes #19

### CODE REVIEW

**Comment by donvreug** [comment]
Brilliant, looking forward to trying it.  Cheers.

**Comment by donvreug** [comment]
I could not get the [TreatAsInlineTable] option to work.  I got a missing using directive or assembly.  I am referencing both Nett and Nett.Coma.

**Comment by paiden** [comment]
Hmm... there is the public attribute class 'TreatAsInlineTableAttribute' in Nett.dll.

Did you compile the correct branch (topic/inltables)?

Maybe forgot to replace a NugetPackage reference with the self compiled assembly?

**Comment by donvreug** [comment]
Sorry I had not pulled the correct branch.

All works fine now.

Two questions.

In the class below how do I define an inline table for a Dictionary<string, bool> Items?

public UserSettings User { get; set; } = new UserSettings();
public class UserSettings
{
    public bool ApplyProperty1 { get; set; }
    public int Property1 { get; set; }
    public string Property2 { get; set; }
    public double Property3 { get; set; }
    //public DateTime Property4 { get; set; }
    public string[] NumberFormats { get; set; }
    public List<string> List { get; set; }
    public List<string> Variables { get; set; }
    public Dictionary<string, bool> Items { get; set; }
    public Dictionary<string, Item> VariableProperties { get; set; }
}


Also notice the commented DateTime property.  I could not get this to work properly.  When uncommented I kept getting the error…

System.ArgumentOutOfRangeException occurred
  HResult=0x80131502
  Message=The UTC time represented when the offset is applied must be between year 0 and 10,000.
  Source=mscorlib
  StackTrace:
<Cannot evaluate the exception stack trace>

I am using a standard Visual Studio DateTimePicker control.  Any thoughts appreciated.

Thanks for the inline table functionality.

Regards Don

**Comment by paiden** [comment]
To make them inline you can either do
```
[TreatAsInlineTable]
public ItemsDict : Dictionary<string, bool> { };

public class UserSettigs
{
    ItemsDict Items { get; set;}
}
```
or
```
            var config = TomlConfig.Create(cfg =>
                cfg.ConfigureType<Dictionary<string, bool>>(type =>
                    type.TreatAsInlineTable()));

            var s = Toml.WriteString(new UserSettings(), config);
```
The second approach will write all Dict<string, bool> properties in the config as an inline dict.

Regarding the DateTime issue, it is hard to tell. I will have to investigate. But from the error message I suspect that the DateTime object that should get serialized is not initialized correctly?

**Comment by donvreug** [comment]
I am still having some issues getting this working for Dictionary<string, bool> inline tables.

My ConfigSettings class is:

public class ConfigSettings
{
    public UserSettings User { get; set; } = new UserSettings();
    [TreatAsInlineTable]
    public class ItemsDict : Dictionary<string, bool> { }
    public class UserSettings
    {
        public ItemsDict Items { get; set; }
        public Dictionary<string, Item> VariableProperties { get; set; }
    }
    [TreatAsInlineTable]
    public class Item
    {
        public bool Checked { get; set; }
        public string Name { get; set; }
        public string Caption { get; set; }
        public string Unit { get; set; }
        public string NumberFormat { get; set; }
        public string Type { get; set; }
        public bool CalcStats { get; set; }
    }
}

My initial toml file is:

[User]
Items = {first = true, second = false, third = true}
[User.VariableProperties]
fe = {Checked = true, Name = "fe", Caption = "Fe", Unit = "%", NumberFormat = "#0.00", Type = "column", CalcStats = true}

The output toml file is:

[User]

[User.Items]
first = true
second = true
third = true

[User.VariableProperties]
fe = { Checked = true, Name = "fe", Caption = "Fe", Unit = "%", NumberFormat = "#0.00", Type = "column", CalcStats = true }

So as you can see the User.VariableProperties is fine but the User.Items does not get written as an inline table.

In my code I declare an new instance of ConfigSettings.ItemsDict as follows

ConfigSettings.ItemsDict newItems = new ConfigSettings.ItemsDict();

I add some items , then save it out as

settings.Set(s => s.User.Items, newItems, userSource);

Do you have any thoughts on what I might be doing wrong?

Regards

Don

**Comment by paiden** [comment]
This was caused by an additional bug in 'Coma'. The last commit should fix that issue.

**Comment by donvreug** [comment]
When reading the toml file, e.g. var items = settings.Get(s => s.User.Items); 
the entry 
Items = { first = true, second = false, third = true }
causes an exception.

Error.System.IndexOutOfRangeException: Index was outside the bounds of the array.
StackTrace	"   at Nett.TomlTableToTypedDictionaryConverter.Convert(ITomlRoot root, Object value, Type targetType) in D:\\Visual Studio\\Test\\TOML\\Source\\Nett\\TomlTableToTypedDictionaryConverter.cs:line 26\r\n   at Nett.TomlTable.Get(Type t) in D:\\Visual Studio\\Test\\TOML\\Source\\Nett\\TomlTable.cs:line 142\r\n   at Nett.TomlObject.Get[T]() in D:\\Visual Studio\\Test\\TOML\\Source\\Nett\\TomlObject.cs:line 42\r\n   at TOMLSettings.PreferencesForm.ReadConfig() in D:\\Visual Studio\\Test\\AppSettingsTest\\TOMLSettings\\PreferencesForm.cs:line 214"	string

**Comment by paiden** [comment]
And one more bugfix commit... hopefully the last one.

**Comment by donvreug** [comment]
Yes, that looks like it got it.  Thanks very much.

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0122	'DictionaryExtensions.Add<TKey, TValue>(IDictionary<TKey, List<TValue>>, TKey, TValue)' is inaccessible due to its protection level	Nett.UnitTests.Internal	D:\Visual Studio\Test\TOML\Test\Nett.UnitTests.Internal\TomlTableToTypedDictionaryConverterTests.cs	64	Active

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0122	'DictionaryExtensions.Add<TKey, TValue>(IDictionary<TKey, List<TValue>>, TKey, TValue)' is inaccessible due to its protection level	Nett.UnitTests.Internal	D:\Visual Studio\Test\TOML\Test\Nett.UnitTests.Internal\TomlTableToTypedDictionaryConverterTests.cs	65	Active

**Comment by donvreug** [comment]
Those two errors occurred when I tried to compile the solution.

**Comment by paiden** [comment]
Wird, it compiles fine for me.

Maybe try to do a 
git clean -fxd
git reset --hard

And then a full rebuild.

**Comment by donvreug** [comment]
No luck.  Followed those instructions but still get the same errors after a rebuild.

**Comment by paiden** [comment]
In that case I'm out of ideas. After a fresh clone I can compile the Solution just fine. For now, I can only assume it is a problem on your machine.

So.... I think the inline table functionality is OK for now. Further issues will be separate bug fixes. 

So I will complete the pull request for now to get the functionality into master. Please open new issues if you encounter further problems with inline tables.

**Comment by paiden** [comment]
Ah, this issue happens after the branch gets merged into master. I assume, you merged into master and built, instead of just building the topic branch.

**Comment by donvreug** [comment]
Yes,  Thanks for including this functionality.

**Pull request merged**
